version: "3.9"

services:
  redis:
    image: redis:latest
  django:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
    - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres  
  celery:
    build: .
    command: > 
      bash -c "
        cd app &&
        celery -A djackets_django worker -l INFO
      "
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: > 
      bash -c "
        cd app &&
        celery -A djackets_django beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
      
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db  
volumes:
  postgres_data:
    


    