version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn -w 2 -b 0.0.0.0:8000 --chdir ./app djackets_django.wsgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  celery:
    build: .
    command: > 
      bash -c "
        cd app &&
        celery -A djackets_django worker -l INFO
      "
    volumes:
      - .:/code
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: > 
      bash -c "
        cd app &&
        celery -A djackets_django beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
      
    volumes:
      - .:/code
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/app/media 
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
