# Generated by Django 4.0.1 on 2022-01-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='porductPlaceholder.gif', null=True, upload_to='uploads/'),
        ),
    ]
