# Generated by Django 4.0.1 on 2022-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/uploads/uploads/porductPlaceholder.gif', upload_to='uploads/'),
        ),
    ]
