# Generated by Django 4.0.1 on 2022-02-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flow_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
