# Generated by Django 4.0.1 on 2022-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_flow_token_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('stale', 'Stale'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('pagada', 'Pagada'), ('pendiente', 'pendiente'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='created', max_length=20),
        ),
    ]
