# Generated by Django 4.0.1 on 2022-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('stale', 'Stale'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='created', max_length=20),
        ),
    ]
